version: "3"
services:
  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/code/app
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
